# Generated by Django 3.2 on 2021-04-29 02:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20210429_0654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='languageknown',
            name='fluency',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
