# Generated by Django 3.2 on 2021-04-29 02:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_languageknown_fluency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='educationdetail',
            name='college',
        ),
        migrations.RemoveField(
            model_name='educationdetail',
            name='degree',
        ),
        migrations.AddField(
            model_name='educationdetail',
            name='course',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='educationdetail',
            name='education',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='educationdetail',
            name='specialization',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='educationdetail',
            name='university',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='educationdetail',
            name='graduation_year',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
