# Generated by Django 3.2 on 2021-04-29 02:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20210429_0757'),
    ]

    operations = [
        migrations.AlterField(
            model_name='educationdetail',
            name='education',
            field=models.CharField(choices=[('0', 'Doctorate/PhD'), ('1', 'Masters/Post-Graduation'), ('2', 'Graduation/Diploma'), ('3', '12th'), ('4', '10th')], max_length=100, null=True),
        ),
    ]
