# Generated by Django 3.2 on 2021-04-29 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_alter_educationdetail_education'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='educationdetail',
            name='education',
            field=models.CharField(choices=[('0', 'Doctorate/PhD'), ('1', 'Masters/Post-Graduation'), ('2', 'Graduation/Diploma'), ('3', '12th')], max_length=100, null=True),
        ),
    ]
