# Generated by Django 3.2 on 2021-04-29 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20210429_1050'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='sent_for_verification',
            field=models.BooleanField(default=False),
        ),
    ]
