# Generated by Django 3.2 on 2021-04-30 05:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_userprofile_sent_for_verification'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='portfolio_content',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='prtfolio_file',
            field=models.FileField(blank=True, upload_to='portfolio_file/'),
        ),
    ]
