# Generated by Django 3.2 on 2021-04-30 06:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20210430_1122'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userprofile',
            old_name='prtfolio_file',
            new_name='portfolio_file',
        ),
    ]
