# Generated by Django 3.2 on 2021-04-30 06:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_rename_prtfolio_file_userprofile_portfolio_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='portfolio_file',
        ),
    ]
